2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Configure stats pid to 3102821
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:24:11,276 INFO    MainThread:3102821 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_012411-13o9gq03/logs/debug.log
2023-10-18 01:24:11,277 INFO    MainThread:3102821 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_012411-13o9gq03/logs/debug-internal.log
2023-10-18 01:24:11,277 INFO    MainThread:3102821 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3e447baec0>
2023-10-18 01:24:11,277 INFO    MainThread:3102821 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:24:11,277 INFO    MainThread:3102821 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:24:11,277 INFO    MainThread:3102821 [wandb_init.py:init():593] re-initializing run, found existing run on stack: oxg9ojzt
2023-10-18 01:24:11,279 INFO    MainThread:3102821 [wandb_run.py:_finish():1934] finishing run dwryu/TCN/oxg9ojzt
2023-10-18 01:24:11,279 INFO    MainThread:3102821 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-18 01:24:11,279 INFO    MainThread:3102821 [wandb_run.py:_restore():2151] restore
2023-10-18 01:24:11,280 INFO    MainThread:3102821 [wandb_run.py:_restore():2157] restore done
2023-10-18 01:25:51,615 INFO    MainThread:3102821 [wandb_init.py:init():618] starting backend
2023-10-18 01:25:51,616 INFO    MainThread:3102821 [wandb_init.py:init():622] setting up manager
2023-10-18 01:25:51,619 INFO    MainThread:3102821 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 01:25:51,620 INFO    MainThread:3102821 [wandb_init.py:init():628] backend started and connected
2023-10-18 01:25:51,635 INFO    MainThread:3102821 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 01:25:51,635 INFO    MainThread:3102821 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 01:25:51,635 INFO    MainThread:3102821 [wandb_init.py:init():720] updated telemetry
2023-10-18 01:25:51,636 INFO    MainThread:3102821 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 01:26:08,558 WARNING MainThread:3102821 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Configure stats pid to 3102821
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Loading settings from /workspace/TCN/wandb/settings
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_init.py:_log_setup():528] Logging user logs to /workspace/TCN/wandb/run-20231018_012613-2m3mcr0p/logs/debug.log
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_init.py:_log_setup():529] Logging internal logs to /workspace/TCN/wandb/run-20231018_012613-2m3mcr0p/logs/debug-internal.log
2023-10-18 01:26:13,535 INFO    MainThread:3102821 [wandb_init.py:init():568] calling init triggers
2023-10-18 01:26:13,536 INFO    MainThread:3102821 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 100, 'batch_size': 256}
2023-10-18 01:26:13,536 INFO    MainThread:3102821 [wandb_init.py:init():618] starting backend
2023-10-18 01:26:13,536 INFO    MainThread:3102821 [wandb_init.py:init():622] setting up manager
2023-10-18 01:26:13,537 INFO    MainThread:3102821 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-18 01:26:13,538 INFO    MainThread:3102821 [wandb_init.py:init():628] backend started and connected
2023-10-18 01:26:13,545 INFO    MainThread:3102821 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-18 01:26:13,545 INFO    MainThread:3102821 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-18 01:26:13,545 INFO    MainThread:3102821 [wandb_init.py:init():720] updated telemetry
2023-10-18 01:26:13,545 INFO    MainThread:3102821 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-18 01:26:55,378 WARNING MainThread:3102821 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
